server:
  port: 8082

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # camelCase
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  main:
    allow-bean-definition-overriding: true # allow bean overriding

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jackieyang.rbac
knife4j:
  enable: true
  setting:
    language: zh_cn
